Implemented API feature
KingsleyIbe/leaderboard pull request #3
Opened 2021-12-16 15:32 UTC by KingsleyIbe

In this milestone, I implemented the following:

- Created a new game.
- Implement the "Refresh" button.
- Implement the form "Submit" button (adding new data to API).
- Used async and await JavaScript features to consume the API.
- Didn't implement any styling.

2021-12-16 15:47 UTC, GzimAsani requested changes
# Hi @KingsleyIbe                               
Good job so far! Your code looks fine, good job :+1:  :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Great job with the project it looks really good :muscle: 

## Required Changes ♻️ 
- [ ] _Check inline comments for more information :arrow_double_down:_ 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 15:47 UTC, GzimAsani commented on src/fetchApi.js
> +const postUser = (user, score) => {
- [ ] After I add a user and my score, the name does not get added in the leaderboard
- [ ] After I add the user for the first time, I cannot do the same for the second time the information does not get posted to the API.

2021-12-17 09:12 UTC, KingsleyIbe commented
Hello Gzim,

Thank you for reviewing my project.
The requested changes have been implemented.

2021-12-17 09:25 UTC, Rustamxon7 approved these changes
## Hi @KingsleyIbe   👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-12-17 09:41 UTC, KingsleyIbe commented
Hi Rustamjon,

Thank you for approving my project.

2021-12-17 09:41 UTC, merged